### PR TITLE
Added initial WfExS-backend examples based on toy workflow.

### PR DESCRIPTION
**Pull request by jmfernandez**
I have just added the generated RO-Crates from the execution of two toy workflows with WfExS-backend.

### CODE REVIEW

**Review by lrodrin — APPROVED** [review]

**Review by simleo — CHANGES_REQUESTED** [review]
I'll start from `cosifer-cwl_provenance`.

* The root dataset's `conformsTo` needs to change to that of Workflow Run Crate (i.e., it should not conform to `https://w3id.org/ro/wfrun/provenance/0.1`, but only to the other three profiles), since the tool execution is not recorded. The recorded actions are the "consolidation" (what is this, by the way?) and three executions of the workflow.

* The crate needs to specify a `license`.

* The root dataset needs to link to the `CreateAction` instances via `mentions`.

* There are duplicate entries in the workflows' `input` and `output` that need to be eliminated. This is not handled by ro-crate-py, so it has to be taken care of in the library user's code. Other lists in the crate also have duplicates, e.g. the workflow's `softwareRequirements`. BTW, `softwareRequirements` is a property of `SoftwareApplication`, so `SoftwareApplication` should be added to the workflow's type list.

* The workflow lists itself in `hasPart`. It should only list the tools (only one in this case). However, since it's a Workflow Run Crate, `hasPart` can be omitted altogether.

* Input and output files should either be included in the crate or be retrievable via download. So [data_matrix.csv](https://raw.githubusercontent.com/PhosphorylatedRabbits/cosifer/f2e2a259d218b9a56a01d84bc9d6a7cd7c8d9bf1/examples/interactive/data_matrix.csv) is ok, but the `nih:` URIs are another matter. What should the crate user do with e.g. `nih:sha-256;95fe-414b-b4e0-e193-6230-ea67-cd55-4ca8-cf30-6281-0870-0748-5d76-2df3-67b7-8bf4;9`? How can the file be retrieved?

`cosifer-cwl_staged` is similar to `cosifer-cwl_provenance`, but does not have the workflow executions. Remarks are similar to the ones above, with the following differences:

* Since the only action is the consolidation, which is not a workflow execution, this crate should conform to Process Run Crate and Workflow RO-Crate, but not Workflow Run Crate or Provenance Run Crate.

* The workflow has `input` but not `output`. They could both be omitted though.

The `cosifer-nxf*` crates have issues similar to the ones above. In addition:

* The workflow's `input` lists both an `outputsDir` and an `outputs-dir` parameter, but only the former is present in the workflow.

* The workflow lists `nextflow.config` in `hasPart`, but `hasPart` should only list the tools orchestrated by the workflow. `nextflow.config` should be listed in the action's "object" (see [referencing configuration files](https://www.researchobject.org/workflow-run-crate/profiles/0.1/process_run_crate#referencing-configuration-files)). `hasPart` in the workflow can be omitted altogether.

**Comment by jmfernandez** [comment]
I have been updating previous examples, as well as adding new, real life, ones. New examples in this repo only include the generated ro-crate-metadata.json and either a copy of the workflow or its packed version, as the used inputs and containers need several GBs.

**Comment by jmfernandez** [comment]
I have revised the main issues. I still have to revise the other ones, and figure out the best way to add and semantically relate a README file describing the meaning and usage of the different schemes to the generated RO-Crates

**Comment by simleo** [comment]
The biggest issue with the recent changes is that `CreateAction` instances have `instrument` properties with multiple values. `CreateAction` instances need to have a single `instrument`, pointing to the application used to perform the action. In particular, the action that represents the workflow run must have the workflow itself as its `instrument`. This is crucial to reconstruct the mapping between the action's actual values and the formal parameters. If you wish to list dependencies somehow, it's better to include them in the application's `SoftwareRequirements` as you have been doing all along. Multiple values for `instrument` break `runcrate report` BTW.

Other issues I've found with the latest changes:

* The root dataset should not have an `"about": {"@id": "README.md"}`; it's the readme that is about the crate, not the other way around, so the "README.md" entity should have an `"about": {"@id": "./"}`.

* The entities used to represent Docker images link to a JSON file via `hasPart`. I think this should be `subjectOf` instead, though it's redundant since the entities that represent the JSON files have an `about` pointing to the Docker image entities. By the way, what are these JSON files? Do they conform to some standard for describing images / containers?

**Comment by jmfernandez** [comment]
> The biggest issue with the recent changes is that `CreateAction` instances have `instrument` properties with multiple values. `CreateAction` instances need to have a single `instrument`, pointing to the application used to perform the action. In particular, the action that represents the workflow run must have the workflow itself as its `instrument`. This is crucial to reconstruct the mapping between the action's actual values and the formal parameters. If you wish to list dependencies somehow, it's better to include them in the application's `SoftwareRequirements` as you have been doing all along. Multiple values for `instrument` break `runcrate report` BTW.

I understand it, I have applied the change. The reason I added multiple instruments to the CreateAction is that I realized a workflow can be run in different containerization modes, so fully describing the workflow execution (not the workflow itself) requires either adding all the software requirements under `instrument`, declaring all the instruments together in a collection and adding the collection under instrument or declaring them in a different place (although not completely correct, under `softwareAddOn`). For instance, an nf-core workflow can be run either using conda mode (so the dependencies should be linked in some place) or singularity (the used containers should be pointed out), plus other tangential software execution details, like a queue system.

So, my conclusion is that the containers and the container engine should not appear under softwareRequirements of the computational workflow as such, as they could not appear in a different execution. So, in the mean time, I'm declaring them under [softwareAddOn](https://schema.org/softwareAddOn).

So, in the long term, I think we should distinguish between the workflow as SoftwareSourceCode (the [targetPlatform](https://schema.org/targetPlatform) is the workflow engine) and the instantiated workflow as SoftwareApplication (the softwareRequirements are the workflow engine, the containers, etc...). What do you think?

> 
> Other issues I've found with the latest changes:
> 
>     * The root dataset should not have an `"about": {"@id": "README.md"}`; it's the readme that is about the crate, not the other way around, so the "README.md" entity should have an `"about": {"@id": "./"}`.
> 

Thanks! I didn't realize I put the relation in the wrong way.

>     * The entities used to represent Docker images link to a JSON file via `hasPart`. I think this should be `subjectOf` instead, though it's redundant since the entities that represent the JSON files have an `about` pointing to the Docker image entities. By the way, what are these JSON files? Do they conform to some standard for describing images / containers?

These  JSON are metadata gathered by WfExS-backend, and depending on whether Singularity/Apptainer or Docker/Podman have one or another format. They help WfExS-backend to identify when the original container and the contents from the cache (or RO-Crate) do not match. I have just added  a couple of paragraphs to the automatically included README.md files, giving some details.

Following with your last questions, when docker or podman modes have been used to run the workflow, the metadata of the images can be obtained using `docker inspect imagetag` or `podman inspect imagetag`. This metadata is an array describing each layer of the image, and is preserved under the `manifests` key. The other keys keep digests and an id which is stable with docker save + docker load operations.

When Singularity/Apptainer mode is used for the workflow execution, container images can come from either http requests or from docker registries. Any of them are materialized by `singularity pull`, but that command does not preserve the metadata from docker registries, like the original id and original layers of the container. So, for singularity images created from docker ones the code asks through REST API to get the original container image metadata from the registry.

So, although part from those JSON files contain original metadata, they are augmented with additional details.

**Comment by jmfernandez** [comment]
I have updated all the examples, so they are now using `ContainerImage`. Also, they should be reflecting the cases where the original source of the container is a Docker registry, but the tool used to materialize it was singularity/apptainer

**Comment by simleo** [comment]
Version 0.3 of the profiles, which include [the specs on container images](https://github.com/ResearchObject/workflow-run-crate/pull/64), has been [released](https://github.com/ResearchObject/workflow-run-crate/pull/65), so you can change the `conformsTo` entries accordingly.

[ro-crate-py 0.9.0](https://pypi.org/project/rocrate/0.9.0/) has also been released and includes https://github.com/ResearchObject/ro-crate-py/pull/162, so you can use it to add the whole context.

**Comment by jmfernandez** [comment]
Nice! I'm doing it along these days!

**Comment by simleo** [comment]
Merging to give a home to the examples. Remaining updates can be done in a subsequent PR

**Pull request merged**
