### PR TITLE
Proposed draft changes to allow for a galaxy history export to be accepted by cwlprov_to_crate.py

### PR DESCRIPTION
**Pull request by pauldg**
Note: We use a history export  for now since galaxy does not yet support the export of workflow runs, but it is safe to assume that the metadata structure will be largely the same.

Proposed (working) changes to cwlprov_to_crate.py to allow a galaxy history export (and a workflow definition derived from the galaxy history) as input. 
This includes the extraction of a CWLProv document from the galaxy history export metadata.

Changes:

1. To differentiate between a "galaxy workflow run" and a cwl workflow run I added a workflow-type argument. 
    Therefore I had to move the location where the global `WORKFLOW_BASENAME` was defined to `__init__`
    I differentiate between "galaxy workflow run" and a cwl workflow run in the following functions:
    `__init__`, `build` and `add_action`

2. To include a the galaxy workflow definition I created the `add_ga_workflow` function
3. TODO: reading in the galaxy workflow definition in similar fashion as `get_workflow` does for the cwl workflow definition. As I'm missing this part, I'm also missing some of the fields in `ro-crate-metadata.json`

Please let me know any suggestions.

### CODE REVIEW

**Review by simleo — CHANGES_REQUESTED** [review]
I've made some adjustments to make unit tests pass and remove unnecessary modules. In particular, I've added a unit test stub for the Galaxy test case (`test_ga_export` in `test_make_crate.py`) that checks what's already being generated correctly. The main problem with the Galaxy crate is that the main `CreateAction` has nothing under `object` and `result`:

```json
{
    "@id": "#24f8f050-4cd1-485c-af7c-8777af402a5a",
    "@type": "CreateAction",
    "endTime": "2022-10-04T10:44:08.416487",
    "instrument": {"@id": "ga_export.ga"},
    "name": "Run of ga_export.ga#main",
    "object": [],
    "result": [],
    "startTime": "2022-10-04T10:44:08.416693"
}
```

The `result` should link to the `tutorial_output.txt_4.txt` `File`. The `object` matter is a bit more complicated since Galaxy's definition of "step" includes workflow inputs (see e.g. [this tutorial](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-editor/tutorial.html)), while we follow CWL and consider only data processing stages as steps. The test workflow added by this PR has the following diagram:

ga_wf_cat_randomlines

As shown graphically, however, the Galaxy GUI can tell inputs from tools: I guess it does it by checking for `"tool_id"` to be `null` in the workflow definition, so we could do the same. The `object` of the above action should link to `"dataset2.txt_1.txt"` and `"dataset1.txt_2.txt"`, while the `CreateAction` entities corresponding to file uploads should go away, since they're not part of the workflow execution. I guess this kind of problem will not be present when workflow run export will be available.

Actions corresponding to tool executions look fine instead, except for the missing `instrument`:

```json
{
    "@id": "#f22a599c-1199-4c1e-a2a5-3b6f418cab17",
    "@type": "CreateAction",
    "endTime": "2021-06-23T10:46:44.738703",
    "instrument": null,
    "name": "Run of ga_export.ga#main/cat1",
    "object": [
        {"@id": "dataset2.txt_1.txt"},
        {"@id": "dataset1.txt_2.txt"}
    ],
    "result": [
        {"@id": "Concatenate_datasets_on_data_2_and_data_1_3.txt"}
    ],
    "startTime": "2021-06-23T10:46:28.351123"
},
{
    "@id": "#2859839f-4f67-46e3-afb9-b7b5f4a3b23a",
    "@type": "CreateAction",
    "endTime": "2021-06-23T10:47:04.837750",
    "instrument": null,
    "name": "Run of ga_export.ga#main/random_lines1",
    "object": [
        {"@id": "Concatenate_datasets_on_data_2_and_data_1_3.txt"}
    ],
    "result": [
        {"@id": "tutorial_output.txt_4.txt"}
    ],
    "startTime": "2021-06-23T10:46:28.526901"
}
```

There are many other occurrences of `null` in the crate, which will have to go away -- I guess it's due to the fact that the workflow definition is not used yet.

The `provenance_profile` module looks like it's derived from the module by the same name in cwltool. I'm not sure whether the original needs to be credited, perhaps it's different enough to be considered a separate thing. @mr-c? On the other hand, since in the Galaxy case there is no actual RO (the `Provenance` instance is created directly from the history export), maybe the Galaxy converter should be a separate tool that directly outputs RO-Crates instead (the plan is for future versions of cwltool to be able to do that as well).

A note on the example workflow: is it something you created? If not, what's its license? This info should be added to `test/data/README.md`.

**Comment by pauldg** [comment]
Thank you for these changes, looks good!
As for the issues you identified, I think most of those can indeed be resolved by parsing the Galaxy workflow definition.

The workflow used comes from a Galaxy tutorial, I will credit it in the `README`

**Comment by stain** [comment]
As discussed last week, we'll split out `runcrate` as a separate GitHub repo and then we can re-raise this pull request there. Leaving this issue open until then.

**Comment by pauldg** [comment]
Now that https://github.com/galaxyproject/galaxy/pull/15101 was merged, I'd like to integrate developments made there back into this work before re-raising this pull request.

**Comment by stain** [comment]
Closing as we think this is now all in Galaxy's code

**Pull request closed without merging**
